services:
  app:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
      - .env.local
    environment:
      APP_ENV: development
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./:/var/www/html
