# Building the production image locally
services:
  app:
    build:
      context: .
      target: production
    env_file:
      - .env.base
      - .env.production
    ports:
      - '80:8080'
      - '443:8443'
