# For live mounting the source code and local development
services:
  app:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    env_file:
      - .env.base
      - .env.local
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./:/var/www/html
