services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    env_file:
      - .env
      - .env.production
    build:
      context: .
      target: production # <- production stage
    restart: always
    depends_on:
      - db
    ports:
      - '80:8080'
      - '443:8443'
    # volumes:
    #   - storage_data:/var/www/html/storage

volumes:
  db_data:
  # storage_data:
