services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.base
    volumes:
      - db_data:/var/lib/mysql

  app:
    restart: always
    depends_on:
      - db

volumes:
  db_data:
