services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    environment:
      APP_ENV: development
    env_file:
      - .env
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: always
    depends_on:
      - db
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./:/var/www/html

volumes:
  db_data:
