name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: registry.aabidk.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: production
          tags: |
            registry.aabidk.dev/cust-mang:latest
            registry.aabidk.dev/cust-mang:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Coolify deploy
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL }}' --header "Authorization: Bearer ${{ secrets.COOLIFY_WEBHOOK_TOKEN }}"
